-- Implements some common functionality alongside the barebones building
-- Supports the following "settings" in the building.toml file:
--  -> launchpad: [name, bounds, type]: for launchpads
--  -> interact: [script]: script gets passed ID of the building