radius = 6360_000.000000000000 # meters
mass = 5.9722e24

[far_color]
	x = 0.2
	y = 0.4
	z = 1.5

[atmo]
	exponent = 1.5
	sunset_exponent = 2.5
	radius = 6500_000.000000000000 # meters, 0 for no atmosphere
	[atmo.main_color]
		x = 0.7
		y = 0.8
		z = 1.7
	[atmo.sunset_color]
		x = 1.0
		y = 0.3
		z = 0.1

[surface]


	images = [	{ name = "heightmap", path = "rss_textures:earth/hmap.png"},
				{ name = "colormap", path = "rss_textures:earth/color.png"}]

	script_path = "planets/earth/surface.lua"	# Will automatically be created for you
	has_water = true				# Does the planet have water
	max_height = 50_000.0

	[surface.noise]
		seed = 0
		interp = 2		# 	0 = Linear < 1 = Hermite < 2 = Quintic

	[surface.lod]
		max_depth = 10				# Max LOD depth allowed
		coef_a = 2.0				# LOD coefficient A
		coef_b = 3
