radius = 1737_100.0 # meters
mass = 7.342e22

[far_color]
	x = 0.4
	y = 0.4
	z = 0.4

[surface]

	script_path = "planets/moon/surface.lua"
	has_water = false				# Does the planet have water
	max_height = 50_000.0

	[surface.noise]
		seed = 0
		interp = 2		# 	0 = Linear < 1 = Hermite < 2 = Quintic

	[surface.lod]
		max_depth = 10				# Max LOD depth allowed
		coef_a = 2.0				# LOD coefficient A
		coef_b = 3
